/* ============================================================================
   Shopee Fee Dataset — untuk fitur "AI Insight" di Pricing Calculator
   ----------------------------------------------------------------------------
   Sumber resmi Shopee Seller Centre:
     - Biaya Administrasi / Layanan per kategori  (efektif 25-02-2026)
     - Biaya Gratis Ongkir XTRA per kategori       (efektif 02-05-2026)
     - Biaya Promo XTRA                            (flat 4,5%, 31-12-2025)

   Tiap entri:
     c    = kategori utama
     s    = sub kategori (yang muncul sebagai hasil)
     adm  = Biaya Layanan Non-Star / Star+ (%)
     mall = Biaya Layanan Shopee Mall (%)
     ox   = kode tier Ongkir XTRA (A–H) → lihat SHOPEE_OX
     k    = kata kunci pencarian (jenis produk + sinonim umum)

   Promo XTRA = flat 4,5% untuk semua tipe penjual (cap Rp60.000/kuantitas).
   Ongkir XTRA per kode: [Ukuran Biasa %, Ukuran Khusus %] (cap Rp40.000/Rp60.000).
   ========================================================================== */

window.SHOPEE_PROMO_XTRA = 4.5;

window.SHOPEE_OX = {
  A: [1,   2.5],
  B: [2,   3.5],
  C: [3.5, 5],
  D: [5.5, 7],
  E: [6,   7.5],
  F: [6.5, 8],
  G: [7.5, 9],
  H: [8,   9.5]
};

// Sinonim / istilah sehari-hari → kata baku yang dipakai di keyword.
window.SHOPEE_SYNONYMS = {
  // Elektronik
  "cover": "sarung", "case": "casing", "casan": "charger", "cas": "charger",
  "hp": "handphone", "henpon": "handphone", "ponsel": "handphone",
  "tv": "televisi", "kulkas": "kulkas", "lemari es": "kulkas",
  "softlens": "lensa kontak", "softlense": "lensa kontak",
  "make up": "kosmetik", "makeup": "kosmetik",
  "skincare": "perawatan wajah", "skin care": "perawatan wajah",
  "headset": "headphone", "earphone": "earphone", "speaker": "speaker",
  "laptop": "laptop", "powerbank": "powerbank", "power bank": "powerbank",
  "kabel data": "kabel handphone", "charger wireless": "wireless charger",
  "magsafe": "wireless charger", "fast charging": "charger",
  "teflon": "penggorengan", "wajan": "penggorengan", "kuali": "penggorengan",
  "catokan": "alat kecantikan", "hairdryer": "hair dryer",
  "galon": "dispenser", "rice cooker": "penanak nasi", "magic com": "penanak nasi",
  "kukus": "steamer", "dangdang": "steamer", "magic jar": "penanak nasi",
  "kipas": "kipas angin", "ac": "ac", "setrika": "setrika", "blender": "blender",
  "kamera": "kamera", "drone": "drone", "cctv": "kamera keamanan",
  "keyboard": "keyboard", "mouse": "mouse", "monitor": "monitor", "printer": "printer",
  "flashdisk": "flashdisk", "ssd": "ssd", "harddisk": "hard disk",
  // Rumah & Furniture
  "kursi": "kursi", "meja": "meja", "lemari": "lemari", "sofa": "sofa",
  "kasur": "matras", "bantal": "bantal", "sprei": "sprei", "bedcover": "bed cover",
  "lampu": "lampu", "gorden": "tirai", "karpet": "karpet", "jam dinding": "jam dinding",
  "cermin": "cermin", "vas": "vas bunga", "tirai": "tirai",
  "tempat sampah": "tempat sampah", "laundry": "laundry bag",
  "ember": "ember", "sapu": "sapu", "pel": "kain pel",
  // Fashion
  "sepatu": "sepatu", "sandal": "sandal", "tas": "tas", "dompet": "dompet",
  "jam": "jam tangan", "kacamata": "kacamata", "cincin": "cincin",
  "emas": "logam mulia", "perhiasan": "perhiasan",
  "jilbab": "hijab", "kerudung": "hijab", "khimar": "hijab",
  "gamis": "gamis", "abaya": "abaya", "kaftan": "kaftan",
  "helm": "helm", "velg": "velg",
  // Otomotif
  "aki": "aki", "ban": "ban", "oli": "oli",
  "sarung jok": "jok", "karpet mobil": "karpet mobil", "parfum mobil": "parfum mobil",
  "sparepart": "suku cadang",
  // Makanan
  "kopi": "kopi", "teh": "teh", "snack": "makanan ringan", "cemilan": "makanan ringan",
  "beras": "beras", "minyak goreng": "minyak", "gula": "gula", "tepung": "tepung",
  "nugget": "makanan beku", "bakso": "makanan beku", "sosis": "makanan beku",
  "dimsum": "makanan beku", "gyoza": "makanan beku", "siomay": "makanan beku",
  "tempe": "makanan segar", "tahu": "makanan segar", "jamur": "jamur",
  "coklat": "cokelat", "permen": "permen", "roti": "roti", "kue": "kue",
  // Kesehatan
  "kosmetik": "kosmetik", "lipstik": "lipstik", "bedak": "bedak",
  "mainan": "mainan", "boneka": "boneka", "buku": "buku",
  "propolis": "suplemen", "jamu": "obat", "herbal": "suplemen",
  "oksimeter": "oximeter", "tensimeter": "alat ukur tekanan darah",
  "sabun cuci tangan": "hand sanitizer",
  // Hewan
  "kucing": "kucing", "anjing": "anjing", "ikan hias": "ikan",
  "akuarium": "aquarium", "pakan": "makanan hewan"
};

window.SHOPEE_FEES = [
  /* ===================== ELEKTRONIK ===================== */
  // Audio
  { c:"Audio", s:"Earphone, Headphone, & Headset", adm:6.75, mall:7.2, ox:"D",
    k:["earphone","headphone","headset","earbuds","tws","handsfree","true wireless","neckband",
       "gaming headset","bone conduction","in ear monitor","iem","gaming earphone","bluetooth headphone",
       "earphone kabel","headphone gaming","bass earphone"] },
  { c:"Audio", s:"Perangkat Audio & Speaker", adm:9.0, mall:7.2, ox:"D",
    k:["speaker","home theater","karaoke","av receiver","soundbar","sound system","speaker bluetooth",
       "speaker aktif","subwoofer","amplifier rumah","speaker outdoor","speaker portable",
       "speaker mini","speaker tws","party speaker","mesin karaoke"] },
  { c:"Audio", s:"Mikrofon & Aksesoris", adm:9.0, mall:7.2, ox:"D",
    k:["mikrofon","mic","microphone","clip on","mic kondenser","mic wireless","mic karaoke",
       "mic gaming","boom mic","phantom power","mic recording","microphone usb"] },
  { c:"Audio", s:"Amplifier & Mixer", adm:9.0, mall:7.2, ox:"D",
    k:["amplifier","mixer","power amplifier","mixing console","audio mixer","eq","equalizer"] },
  { c:"Audio", s:"Kabel & Konverter Audio & Video", adm:9.0, mall:9.95, ox:"D",
    k:["kabel audio","konverter","hdmi","kabel video","aux","jack 3.5","kabel rca","optical cable",
       "audio splitter","hdmi switch","kabel xlr","converter hdmi"] },
  { c:"Audio", s:"Media Player", adm:9.5, mall:7.7, ox:"D",
    k:["mp3","mp4","media player","cd player","dvd player","radio","tape","voice recorder",
       "perekam suara","mp3 player","walkman","blu-ray player"] },

  // Elektronik (rumah tangga & listrik)
  { c:"Elektronik", s:"Kelistrikan", adm:10.0, mall:10.2, ox:"F",
    k:["stop kontak","kabel listrik","saklar","bel","alarm","anti petir","penghemat listrik",
       "terminal listrik","steker","colokan","kabel roll","stabilizer","ups","kabel extension",
       "grounding","mcb","fuse","lampu darurat","emergency lamp"] },
  { c:"Elektronik", s:"Baterai", adm:9.5, mall:7.7, ox:"D",
    k:["baterai","battery","aa","aaa","baterai abc","baterai alkaline","baterai rechargeable",
       "baterai 9v","baterai lithium","baterai kamera","baterai jam"] },
  { c:"Elektronik", s:"Perangkat Dapur (Elektronik)", adm:6.5, mall:7.2, ox:"D",
    k:["dispenser","kompor","kompor listrik","blender","mixer","air fryer","microwave","oven",
       "penanak nasi","rice cooker","magic com","juicer","mesin kopi","kulkas","freezer",
       "kompor gas","food processor","slow cooker","panci presto","presto","pressure cooker",
       "panci elektrik","panci listrik","rice steamer","pembuat roti","bread maker",
       "pemanggang roti","air fryer oven","deep fryer","panci masak","steamer kukus",
       "electric steamer","espresso machine","nespresso","coffee maker","drip coffee",
       "pour over","moka pot","aeropress","milk frother","ice maker","yogurt maker",
       "dehydrator","vacuum sealer","food sealer","chopper listrik","hand mixer",
       "stand mixer","waffle maker","toaster","mini oven","oven tangkring","microwave oven",
       "coffee grinder","electric kettle","teko listrik","french press","cold press juicer"] },
  { c:"Elektronik", s:"Peralatan Listrik Besar (AC, Mesin Cuci)", adm:6.5, mall:7.2, ox:"D",
    k:["ac","air conditioner","mesin cuci","pengering pakaian","kipas angin","pendingin ruangan",
       "ac split","ac portable","ac window","washing machine","dryer","spin dryer","exhaust fan",
       "kipas angin berdiri","kipas duduk","standing fan","ceiling fan","tower fan"] },
  { c:"Elektronik", s:"Peralatan Listrik Kecil", adm:6.5, mall:7.2, ox:"D",
    k:["setrika","mesin uap","purifier","air purifier","dehumidifier","penyedot debu",
       "vacuum cleaner","robot vacuum","sapu robot","mesin jahit","vacuum","robot pel",
       "vacuum portable","handheld vacuum","humidifier","diffuser elektrik","ion air purifier"] },
  { c:"Elektronik", s:"TV & Aksesoris", adm:6.5, mall:7.2, ox:"D",
    k:["tv","televisi","antena tv","bracket tv","tv box","receiver tv","smart tv","led tv",
       "oled tv","qled","android tv","4k tv","8k tv","tv 32 inch","tv 43 inch","tv 55 inch",
       "android box","chromecast","firestick","mi box","set top box","stb"] },
  { c:"Elektronik", s:"Proyektor & Aksesoris", adm:5.25, mall:4.2, ox:"C",
    k:["proyektor","projector","layar proyektor","pointer","mini projector","proyektor mini",
       "pocket projector","laser projector","4k projector","smart projector"] },
  { c:"Elektronik", s:"Remot Kontrol", adm:9.0, mall:7.2, ox:"D",
    k:["remot","remote","remot tv","remote control","universal remote","remot ac","remot universal"] },
  { c:"Elektronik", s:"Rokok Elektronik & Shisha", adm:9.0, mall:7.2, ox:"D",
    k:["vape","rokok elektronik","pods","liquid","shisha","mod","hookah","pod system",
       "disposable vape","coil vape","liquid rokok elektrik"] },

  // Gaming & Konsol
  { c:"Gaming & Konsol", s:"Konsol Game", adm:9.5, mall:7.7, ox:"D",
    k:["playstation","ps4","ps5","xbox","nintendo","switch","psp","konsol game","wii",
       "ps vita","game boy","retro game","gaming console","ps3","xbox one","xbox series"] },
  { c:"Gaming & Konsol", s:"Video Game", adm:9.5, mall:7.7, ox:"D",
    k:["video game","kaset game","game pc","game ps","cd game","dvd game","game switch",
       "game xbox","game nintendo","steam key","game digital"] },
  { c:"Gaming & Konsol", s:"Aksesoris Konsol", adm:9.0, mall:7.2, ox:"D",
    k:["stik ps","controller","joystick","aksesoris konsol","stik game","gamepad",
       "racing wheel","flight stick","ps controller","xbox controller","dualsense",
       "cooling stand","charging dock konsol"] },

  // Handphone & Aksesoris
  { c:"Handphone & Aksesoris", s:"Handphone", adm:5.25, mall:4.7, ox:"A",
    k:["handphone","hp","smartphone","ponsel","iphone","samsung","xiaomi","oppo","vivo",
       "realme","poco","infinix","tecno","motorola","nokia","redmi","oneplus","nothing phone",
       "hp gaming","hp kamera","hp murah"] },
  { c:"Handphone & Aksesoris", s:"Tablet", adm:5.25, mall:4.7, ox:"A",
    k:["tablet","ipad","tab","android tablet","samsung tab","tab s","ipad pro","ipad air",
       "ipad mini","drawing tablet android","tablet gaming","tablet murah"] },
  { c:"Handphone & Aksesoris", s:"Aksesoris Handphone", adm:10.0, mall:10.2, ox:"D",
    k:["casing","case","softcase","charger","casan","kabel data","powerbank","anti gores",
       "tempered glass","pelindung layar","phone holder","tongsis","pouch hp","kepala charger",
       "kabel charger","wireless charger","magsafe","ring holder","pop socket","pop grip",
       "selfie stick","tripod hp","kamera clip on hp","lensa hp","flash hp","power bank",
       "fast charger","type c","micro usb","lightning cable","tali hp","strap hp",
       "holder motor hp","car holder","dashboard holder","charging dock","kabel usb"] },
  { c:"Handphone & Aksesoris", s:"Perangkat Wearable", adm:9.5, mall:7.7, ox:"D",
    k:["smartwatch","jam pintar","fitness tracker","perangkat vr","pelacak gps","gps tracker",
       "smart band","health band","apple watch","galaxy watch","amazfit","garmin","mi band",
       "vr headset","meta quest","smart ring","ar glasses"] },
  { c:"Handphone & Aksesoris", s:"Kartu Perdana", adm:9.5, mall:7.7, ox:"D",
    k:["kartu perdana","perdana","sim card","kartu sim","telkomsel","xl","indosat",
       "tri","by.u","esim","starter pack"] },
  { c:"Handphone & Aksesoris", s:"Walkie Talkie", adm:9.5, mall:7.7, ox:"D",
    k:["walkie talkie","ht","handy talky","radio komunikasi","handie talkie"] },

  // Kamera & Drone
  { c:"Kamera & Drone", s:"Kamera", adm:6.5, mall:7.2, ox:"D",
    k:["kamera","dslr","mirrorless","kamera pocket","action cam","gopro","kamera analog",
       "kamera instan","camcorder","kamera digital","instax","polaroid","kamera 4k",
       "vlog camera","kamera fujifilm","kamera sony","kamera canon","kamera nikon"] },
  { c:"Kamera & Drone", s:"Lensa", adm:6.5, mall:7.2, ox:"D",
    k:["lensa","lens","lensa kamera","lensa prime","lensa zoom","lensa wide","lensa macro",
       "lensa tele","lensa portrait","kit lens","fisheye","lensa mirrorless","lensa dslr"] },
  { c:"Kamera & Drone", s:"Drone", adm:6.5, mall:7.2, ox:"D",
    k:["drone","quadcopter","dji","drone kamera","mini drone","fpv drone","racing drone",
       "drone foto","drone video","aerial photography"] },
  { c:"Kamera & Drone", s:"Kamera Keamanan", adm:9.5, mall:7.7, ox:"D",
    k:["cctv","kamera cctv","dvr","kamera keamanan","kamera pengintai","ip camera","nvr",
       "kamera outdoor","kamera indoor","smart cam","bel kamera","doorbell camera","wifi camera",
       "kamera tersembunyi"] },
  { c:"Kamera & Drone", s:"Aksesoris Kamera", adm:9.5, mall:10.2, ox:"D",
    k:["tripod","gimbal","stabilizer","flash kamera","tas kamera","memori kamera",
       "aksesoris kamera","tripod kamera","monopod","slider kamera","rain cover kamera",
       "cage kamera","follow focus","remote kamera","sd card","memory card","kartu memori"] },
  { c:"Kamera & Drone", s:"Aksesoris Lensa", adm:9.5, mall:7.2, ox:"D",
    k:["filter lensa","hood lensa","cap lensa","adaptor lensa","lens filter","uv filter",
       "nd filter","cpl filter","step up ring","lens adaptor"] },
  { c:"Kamera & Drone", s:"Perawatan Kamera", adm:9.5, mall:7.2, ox:"D",
    k:["dry box","cleaning kit kamera","silica gel","blower","lenspen","kain microfiber",
       "sensor cleaner","kaset silica gel","drying cabinet"] },

  // Komputer & Aksesoris
  { c:"Komputer & Aksesoris", s:"Laptop", adm:5.25, mall:4.7, ox:"A",
    k:["laptop","notebook","macbook","ultrabook","chromebook","gaming laptop","laptop tipis",
       "laptop bisnis","laptop pelajar","laptop second","laptop murah","laptop 14 inch",
       "laptop 15 inch","laptop 13 inch","asus","lenovo","hp laptop","dell","acer","msi"] },
  { c:"Komputer & Aksesoris", s:"Desktop / PC", adm:5.25, mall:4.7, ox:"A",
    k:["pc","desktop","komputer","cpu","pc rakitan","all in one","mini pc","gaming pc",
       "imac","pc office","workstation","server","nuc","brix"] },
  { c:"Komputer & Aksesoris", s:"Monitor", adm:5.25, mall:4.7, ox:"A",
    k:["monitor","layar komputer","lcd monitor","led monitor","4k monitor","gaming monitor",
       "curved monitor","ultrawide","portable monitor","monitor 24 inch","monitor 27 inch",
       "ips monitor","oled monitor","144hz monitor"] },
  { c:"Komputer & Aksesoris", s:"Komponen Desktop & Laptop", adm:5.25, mall:4.2, ox:"B",
    k:["processor","motherboard","vga","ram","power supply","psu","casing pc","heatsink",
       "memory ram","ssd komponen","fan pc","gpu","cpu cooler","thermal paste","pc build",
       "case pc","rgb fan","water cooling","liquid cooling","rtx","rx","intel","amd"] },
  { c:"Komputer & Aksesoris", s:"Penyimpanan Data", adm:6.75, mall:7.2, ox:"C",
    k:["ssd","hard disk","hardisk","flashdisk","usb drive","nas","penyimpanan","hdd",
       "external hard disk","portable ssd","nvme","m.2","sata ssd","harddisk eksternal",
       "usb otg","flashdisk otg","pendrive"] },
  { c:"Komputer & Aksesoris", s:"Printer & Scanner", adm:6.75, mall:7.7, ox:"B",
    k:["printer","scanner","tinta printer","mesin fotokopi","printer thermal","3d printer",
       "ink cartridge","toner","printer laser","printer inkjet","printer epson","printer canon",
       "printer hp","barcode printer","label printer","pos printer","struk printer"] },
  { c:"Komputer & Aksesoris", s:"Keyboard & Mouse", adm:6.75, mall:7.2, ox:"D",
    k:["keyboard","mouse","drawing tablet","keyboard gaming","mouse gaming","mechanical keyboard",
       "keyboard wireless","mouse wireless","trackpad","mouse ergonomis","gaming mouse",
       "keyboard bluetooth","silent keyboard","keyboard rgb","gaming keyboard","razer","logitech"] },
  { c:"Komputer & Aksesoris", s:"Komponen Network", adm:6.75, mall:7.7, ox:"D",
    k:["router","modem","wifi","repeater","switch network","kabel lan","access point",
       "wifi router","modem router","tp-link","mesh wifi","wifi extender","range extender",
       "powerline adapter","network card","wifi adapter","usb wifi"] },
  { c:"Komputer & Aksesoris", s:"Aksesoris Desktop & Laptop", adm:6.75, mall:10.2, ox:"D",
    k:["mouse pad","cooling pad","webcam","usb hub","stand laptop","charger laptop",
       "tas laptop","laptop stand","laptop riser","palm rest","wrist rest","privacy screen",
       "hub usb c","docking station","kvm switch","usb splitter","laptop bag","sleeve laptop",
       "portabel monitor stand","webcam hd"] },
  { c:"Komputer & Aksesoris", s:"Peralatan Kantor", adm:6.75, mall:7.2, ox:"C",
    k:["mesin absensi","penghancur kertas","mesin hitung uang","mesin ketik","paper shredder",
       "finger print absensi","money counter","mesin laminating","laminator","mesin binding"] },
  { c:"Komputer & Aksesoris", s:"Software", adm:6.75, mall:7.2, ox:"D",
    k:["software","aplikasi","windows","antivirus","microsoft office","adobe","lisensi",
       "operating system","windows 11","office 365","vpn","software akuntansi"] },

  /* ===================== FASHION ===================== */
  // Aksesoris Fashion
  { c:"Aksesoris Fashion", s:"Logam Mulia", adm:4.25, mall:3.2, ox:"B",
    k:["emas","logam mulia","perak","platinum","berlian","permata","emas batangan",
       "emas antam","emas perhiasan","perak murni","koin emas"] },
  { c:"Aksesoris Fashion", s:"Perhiasan Berharga", adm:4.25, mall:3.2, ox:"B",
    k:["perhiasan","kalung emas","cincin emas","gelang emas","anting emas","liontin",
       "perhiasan berlian","gelang perak","kalung perak","cincin tunangan","cincin nikah"] },
  { c:"Aksesoris Fashion", s:"Aksesoris Tambahan (Masker)", adm:8.25, mall:10.45, ox:"G",
    k:["masker kain","masker fashion","masker motif","masker polos","masker reusable"] },
  { c:"Aksesoris Fashion", s:"Aksesoris Rambut", adm:9.0, mall:10.2, ox:"H",
    k:["bando","ikat rambut","jepit rambut","scrunchie","hairclip","rambut palsu","wig",
       "claw clip","hair claw","hair tie","pita rambut","mahkota","tiara","hairpin","bobby pin"] },
  { c:"Aksesoris Fashion", s:"Kacamata & Aksesoris", adm:9.0, mall:10.2, ox:"H",
    k:["kacamata","kacamata hitam","sunglasses","frame kacamata","lensa kacamata",
       "kacamata baca","kacamata minus","kacamata fashion","kacamata anti radiasi",
       "bluray glasses","kacamata motor","tempat kacamata"] },
  { c:"Aksesoris Fashion", s:"Topi", adm:9.0, mall:10.2, ox:"H",
    k:["topi","topi baseball","bucket hat","beanie","snapback","trucker hat","topi fedora",
       "topi golf","topi pantai","topi kupluk","topi rajut","beret","topi polos","topi distro"] },
  { c:"Aksesoris Fashion", s:"Ikat Pinggang", adm:9.0, mall:10.2, ox:"H",
    k:["ikat pinggang","sabuk","gesper","belt","ikat pinggang kulit","ikat pinggang wanita",
       "waist bag","fanny pack","sabuk pria"] },
  { c:"Aksesoris Fashion", s:"Anting / Cincin / Kalung / Gelang (Fashion)", adm:9.0, mall:10.2, ox:"H",
    k:["anting","cincin","kalung","gelang","aksesoris fashion","perhiasan imitasi","bangle",
       "choker","body jewelry","anklet","gelang kaki","ear cuff","piercing","kalung fashion",
       "cincin titanium","gelang fashion","anting emas perhiasan"] },
  { c:"Aksesoris Fashion", s:"Dasi", adm:9.0, mall:10.2, ox:"H",
    k:["dasi","dasi kupu","bow tie","dasi panjang","dasi batik","dasi slim","pin dasi"] },
  { c:"Aksesoris Fashion", s:"Sarung Tangan", adm:9.0, mall:10.2, ox:"H",
    k:["sarung tangan","gloves","sarung tangan berkendara","sarung tangan kulit",
       "sarung tangan rajut","sarung tangan casual"] },
  { c:"Aksesoris Fashion", s:"Syal & Selendang", adm:9.0, mall:10.2, ox:"H",
    k:["syal","selendang","scarf","pashmina","syal rajut","scarf motif","snood","neck warmer"] },

  // Fashion Bayi & Anak
  { c:"Fashion Bayi & Anak", s:"Pakaian Anak Laki-Laki", adm:9.0, mall:10.2, ox:"D",
    k:["baju anak laki","kaos anak","kemeja anak","celana anak","jaket anak","seragam anak",
       "baju tidur anak","celana pendek anak","set baju anak laki","baju olahraga anak laki",
       "kostum anak","hoodie anak","sweater anak","baju anak cowok"] },
  { c:"Fashion Bayi & Anak", s:"Pakaian Anak Perempuan", adm:9.0, mall:10.2, ox:"D",
    k:["baju anak perempuan","dress anak","rok anak","kaos anak perempuan","blouse anak",
       "set baju anak perempuan","tutu anak","baju pesta anak","legging anak","jumpsuit anak",
       "baju anak cewek"] },
  { c:"Fashion Bayi & Anak", s:"Pakaian Bayi", adm:9.0, mall:9.95, ox:"D",
    k:["baju bayi","jumper bayi","bodysuit","romper bayi","set bayi","sleepsuit bayi",
       "baju bayi newborn","baju bayi 0-3 bulan","baju bayi baru lahir","kado bayi","layette"] },
  { c:"Fashion Bayi & Anak", s:"Sepatu Anak", adm:9.0, mall:10.2, ox:"D",
    k:["sepatu anak","sandal anak","sneaker anak","sepatu bayi","prewalker","sepatu sekolah anak",
       "sepatu olahraga anak","boots anak","flip flop anak","crocs anak"] },
  { c:"Fashion Bayi & Anak", s:"Aksesoris Bayi & Anak", adm:9.0, mall:10.2, ox:"D",
    k:["tas anak","topi anak","kaos kaki anak","ransel anak","aksesoris anak","kacamata anak",
       "jas hujan anak","payung anak","set aksesoris anak","jam anak"] },

  // Fashion Muslim
  { c:"Fashion Muslim", s:"Mukena & Perlengkapan Sholat", adm:8.25, mall:9.95, ox:"G",
    k:["mukena","sajadah","peci","songkok","kopiah","perlengkapan sholat","mukena travel",
       "baju koko anak","mukena dewasa","sajadah tebal","perlengkapan ibadah","tasbih",
       "sarung sholat","alkitab","mukena anak"] },
  { c:"Fashion Muslim", s:"Pakaian Muslim Wanita", adm:10.0, mall:9.95, ox:"G",
    k:["hijab","jilbab","kerudung","gamis","abaya","khimar","pashmina","tunik","baju muslim wanita",
       "kaftan","hijab instan","segi empat","ciput","baju kurung","dress muslim","outer muslim",
       "baju lebaran","gamis modern","gamis polos","hijab casual","hijab syar'i"] },
  { c:"Fashion Muslim", s:"Pakaian Muslim Pria", adm:8.25, mall:9.95, ox:"G",
    k:["baju koko","gamis pria","sarung","baju melayu","baju muslim pria","sarung tenun",
       "kemeja koko","baju lebaran pria","baju takwa","jubah pria","sarung batik"] },
  { c:"Fashion Muslim", s:"Pakaian Muslim Anak", adm:8.25, mall:9.95, ox:"G",
    k:["baju muslim anak","gamis anak","hijab anak","koko anak","baju koko anak",
       "mukena anak","gamis anak perempuan","gamis anak laki","baju lebaran anak"] },
  { c:"Fashion Muslim", s:"Outerwear Muslim", adm:8.25, mall:9.95, ox:"G",
    k:["cardigan muslim","outer muslim","jaket muslim","rompi muslim","coat muslim",
       "abaya outer","jubah","mantel muslimah"] },

  // Jam Tangan
  { c:"Jam Tangan", s:"Jam Tangan Pria", adm:9.0, mall:10.2, ox:"H",
    k:["jam tangan pria","jam tangan","arloji","jam tangan kasual","jam tangan formal",
       "jam tangan sport","chronograph","jam tangan analog","jam tangan digital","casio",
       "seiko","citizen","fossil","swatch","jam tangan fashion"] },
  { c:"Jam Tangan", s:"Jam Tangan Wanita", adm:9.0, mall:10.2, ox:"H",
    k:["jam tangan wanita","jam tangan cewek","jam tangan fashion wanita","jam tangan rantai",
       "jam tangan bangle","jam tangan diamond","casio wanita","jam tangan cantik"] },
  { c:"Jam Tangan", s:"Jam Tangan Couple", adm:9.0, mall:10.2, ox:"H",
    k:["jam couple","jam tangan pasangan","couple watch","jam tangan kembar"] },
  { c:"Jam Tangan", s:"Aksesoris Jam Tangan", adm:9.0, mall:10.2, ox:"H",
    k:["strap jam","tali jam","baterai jam","kotak jam","tali watch","nato strap",
       "rubber strap","mesh strap","metal strap","pengganti strap","pena jam"] },

  // Koper & Tas Travel
  { c:"Koper & Tas Travel", s:"Koper", adm:10.0, mall:11.7, ox:"G",
    k:["koper","luggage","koper kabin","travel bag","koper hardcase","koper softcase",
       "koper 20 inch","koper 24 inch","koper 28 inch","koper fiber","koper roda 4",
       "koper aluminium","koper murah","koper polo"] },
  { c:"Koper & Tas Travel", s:"Tas Travel", adm:10.0, mall:10.2, ox:"G",
    k:["tas travel","tas duffel","tas lipat","tas serut","travel bag","gym bag","weekender bag",
       "tas gym","dry bag","tas waterproof"] },
  { c:"Koper & Tas Travel", s:"Aksesoris Travel", adm:9.0, mall:10.2, ox:"G",
    k:["passport cover","organizer travel","gembok koper","timbangan koper","bantal leher",
       "tag koper","strap koper","packing cube","travel organizer","neck pillow","ear plug",
       "penutup mata tidur","adaptor travel","travel adaptor","dompet travel"] },

  // Pakaian Pria
  { c:"Pakaian Pria", s:"Atasan Pria", adm:8.25, mall:9.95, ox:"F",
    k:["kaos pria","kemeja pria","kaos polo","baju pria","tanktop","atasan pria","polo shirt",
       "kemeja flanel","kemeja batik","kemeja polos","kaos distro","kaos bola","jersey pria",
       "baju safari","kemeja slim fit","kaos lengan panjang","baju outdoor pria"] },
  { c:"Pakaian Pria", s:"Celana Panjang Pria", adm:8.25, mall:9.95, ox:"F",
    k:["celana panjang pria","cargo","jogger","chino","celana bahan","celana formal",
       "celana kantor","celana katun","celana kain","celana outdoor"] },
  { c:"Pakaian Pria", s:"Celana Jeans Pria", adm:8.25, mall:9.95, ox:"F",
    k:["celana jeans pria","jeans pria","denim pria","celana jeans slim","skinny jeans pria"] },
  { c:"Pakaian Pria", s:"Celana Pendek Pria", adm:8.25, mall:9.95, ox:"F",
    k:["celana pendek pria","celana kolor","celana santai","shorts","celana pantai",
       "celana pendek olahraga pria","celana boxer luar"] },
  { c:"Pakaian Pria", s:"Jaket, Mantel, & Rompi Pria", adm:8.25, mall:9.95, ox:"F",
    k:["jaket pria","mantel","rompi pria","jaket kulit","jaket bomber","jaket varsity",
       "jaket parasut","jaket hoodie","windbreaker","coach jacket","jaket outdoor","parka pria"] },
  { c:"Pakaian Pria", s:"Hoodie & Sweatshirt Pria", adm:8.25, mall:9.95, ox:"F",
    k:["hoodie pria","sweatshirt","sweater pria","crewneck","hoodie zipper","hoodie polos",
       "sweater rajut pria","fleece jacket"] },
  { c:"Pakaian Pria", s:"Pakaian Dalam Pria", adm:8.25, mall:9.95, ox:"F",
    k:["celana dalam pria","boxer","kaos dalam pria","singlet","brief","trunk","pakaian dalam",
       "celana dalam katun","boxer warna"] },
  { c:"Pakaian Pria", s:"Kaos Kaki Pria", adm:10.0, mall:10.2, ox:"F",
    k:["kaos kaki pria","kaos kaki","kaus kaki","ankle socks","long socks","sport socks",
       "kaos kaki pendek","no show socks"] },
  { c:"Pakaian Pria", s:"Pakaian Tidur Pria", adm:8.25, mall:9.95, ox:"F",
    k:["piyama pria","baju tidur pria","sarung pria","celana tidur","set tidur pria"] },

  // Pakaian Wanita
  { c:"Pakaian Wanita", s:"Atasan Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["atasan wanita","kaos wanita","kemeja wanita","blouse","blus","tanktop wanita","bodysuit",
       "outer wanita","cardigan","crop top","off shoulder","kemeja polos wanita","baju kerja wanita",
       "kebaya modern","ruffle top","basic tee","polo wanita"] },
  { c:"Pakaian Wanita", s:"Dress", adm:8.25, mall:9.95, ox:"G",
    k:["dress","gaun","terusan","maxi dress","mini dress","midi dress","wrap dress","floral dress",
       "dress pesta","party dress","sundress","shirt dress","bodycon dress","casual dress"] },
  { c:"Pakaian Wanita", s:"Rok", adm:8.25, mall:9.95, ox:"G",
    k:["rok","rok mini","rok panjang","rok midi","rok plisket","rok lipit","rok tutu",
       "rok batik","rok casual","mini skirt","maxi skirt"] },
  { c:"Pakaian Wanita", s:"Celana & Legging Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["celana wanita","legging","celana panjang wanita","kulot","palazzo","celana bahan wanita",
       "celana kerja wanita","slim pants","wide leg pants","culottes"] },
  { c:"Pakaian Wanita", s:"Celana Jeans Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["jeans wanita","celana jeans wanita","denim wanita","skinny jeans wanita","mom jeans",
       "boyfriend jeans","straight jeans wanita"] },
  { c:"Pakaian Wanita", s:"Pakaian Dalam Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["bra","celana dalam wanita","lingerie","korset","pakaian dalam wanita","bh","bralette",
       "sports bra","wireless bra","push up bra","shapewear","strapless bra"] },
  { c:"Pakaian Wanita", s:"Baju Hamil & Menyusui", adm:8.25, mall:9.95, ox:"G",
    k:["baju hamil","baju menyusui","dress hamil","bra menyusui","celana hamil","atasan hamil",
       "nursing bra","maternity dress","set baju hamil"] },
  { c:"Pakaian Wanita", s:"Pakaian Tidur & Piyama Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["piyama","daster","baju tidur","kimono","sleepwear","set piyama","nightgown",
       "baby doll","silk pajamas","satin pajamas"] },
  { c:"Pakaian Wanita", s:"Set & Outerwear Wanita", adm:8.25, mall:9.95, ox:"G",
    k:["set wanita","setelan wanita","jumpsuit","overall wanita","romper wanita",
       "jaket wanita","blazer wanita","mantel wanita","cape wanita","coat wanita",
       "sweater wanita","hoodie wanita","cardigan wanita","wedding dress","gaun pengantin"] },
  { c:"Pakaian Wanita", s:"Kaos Kaki & Stocking", adm:10.0, mall:10.2, ox:"F",
    k:["kaos kaki wanita","stocking","stoking","pantyhose","kaus kaki wanita","ankle socks wanita"] },

  // Sepatu Pria
  { c:"Sepatu Pria", s:"Sneakers Pria", adm:9.0, mall:10.2, ox:"F",
    k:["sepatu pria","sneakers pria","sepatu kets pria","sepatu casual pria","sepatu nike",
       "sepatu adidas","sepatu converse","slip on pria","sepatu kulit casual","vans pria"] },
  { c:"Sepatu Pria", s:"Sandal Pria", adm:9.0, mall:10.2, ox:"F",
    k:["sandal pria","sandal jepit","sandal gunung","flip flop pria","sandal outdoor",
       "sandal crocs","sandal kesehatan pria","sandal rumah pria"] },
  { c:"Sepatu Pria", s:"Sepatu Formal Pria", adm:9.0, mall:10.2, ox:"F",
    k:["sepatu formal pria","pantofel","oxford","loafer pria","derby","sepatu kantor",
       "sepatu kulit formal","brogue","sepatu pesta pria"] },
  { c:"Sepatu Pria", s:"Boot Pria", adm:9.0, mall:10.2, ox:"F",
    k:["sepatu boot pria","safety boot","boots","chelsea boot","work boot","hiking boot pria",
       "safety shoes","sepatu gunung","steel toe boots"] },
  { c:"Sepatu Pria", s:"Aksesoris & Perawatan Sepatu", adm:9.0, mall:10.2, ox:"F",
    k:["tali sepatu","semir sepatu","insole","perawatan sepatu","parfum sepatu",
       "shoe tree","kotak sepatu","rak sepatu","sikat sepatu","pembersih sepatu"] },

  // Sepatu Wanita
  { c:"Sepatu Wanita", s:"Sneakers Wanita", adm:9.0, mall:10.2, ox:"F",
    k:["sepatu wanita","sneakers wanita","sepatu kets wanita","platform sneaker","chunky sneaker",
       "slip on wanita","sepatu casual wanita","sepatu fashion"] },
  { c:"Sepatu Wanita", s:"Heels", adm:9.0, mall:10.2, ox:"F",
    k:["heels","high heels","sepatu hak","wedges","block heels","kitten heels","stiletto",
       "pumps","sepatu hak tinggi","sepatu pesta wanita","mary jane"] },
  { c:"Sepatu Wanita", s:"Sepatu Flat Wanita", adm:9.0, mall:10.2, ox:"F",
    k:["flat shoes","sepatu flat","ballerina","loafer wanita","mule","slip on flat",
       "sepatu kerja wanita","oxford wanita","monk strap wanita"] },
  { c:"Sepatu Wanita", s:"Sandal Wanita", adm:9.0, mall:10.2, ox:"F",
    k:["sandal wanita","sandal flat","sandal jepit wanita","sandal pesta","sandal heels",
       "sandal casual","sandal strappy","slipper wanita","sandal rumah wanita","crocs wanita"] },

  // Tas Pria
  { c:"Tas Pria", s:"Ransel Pria", adm:9.0, mall:10.2, ox:"G",
    k:["ransel pria","tas ransel","backpack pria","tas punggung","laptop bag","tas sekolah pria",
       "outdoor backpack","hiking backpack","tas kuliah pria","daypack"] },
  { c:"Tas Pria", s:"Tas Selempang & Bahu Pria", adm:9.0, mall:10.2, ox:"G",
    k:["tas selempang pria","sling bag","tas bahu pria","crossbody bag","messenger bag",
       "chest bag","waist bag","fanny pack pria"] },
  { c:"Tas Pria", s:"Dompet Pria", adm:9.0, mall:10.2, ox:"G",
    k:["dompet pria","dompet kartu","dompet lipat","bifold wallet","slim wallet","money clip",
       "dompet kulit pria","card holder","dompet panjang pria"] },
  { c:"Tas Pria", s:"Tas Kerja & Laptop Pria", adm:9.0, mall:10.2, ox:"G",
    k:["tas kerja","tas laptop pria","tas kantor","briefcase","portfolio bag","totebag pria",
       "tas laptop 14 inch","tas laptop 15 inch","executive bag"] },

  // Tas Wanita
  { c:"Tas Wanita", s:"Ransel Wanita", adm:9.0, mall:10.2, ox:"G",
    k:["ransel wanita","tas ransel wanita","backpack wanita","tas punggung wanita",
       "mini backpack","aesthetic backpack","tas sekolah wanita"] },
  { c:"Tas Wanita", s:"Tas Selempang & Bahu Wanita", adm:9.0, mall:10.2, ox:"G",
    k:["tas selempang wanita","sling bag wanita","tas bahu wanita","tas tangan",
       "shoulder bag","crossbody","handbag","tas jinjing kecil","bucket bag","hobo bag",
       "saddle bag","half moon bag"] },
  { c:"Tas Wanita", s:"Tote Bag", adm:9.0, mall:10.2, ox:"G",
    k:["tote bag","tas jinjing","canvas tote","belanja bag","tas belanja kain","eco bag",
       "tas kanvas","grocery bag"] },
  { c:"Tas Wanita", s:"Dompet Wanita", adm:9.0, mall:10.2, ox:"G",
    k:["dompet wanita","dompet panjang","dompet lipat wanita","dompet kulit wanita",
       "clutch dompet","coin purse","card holder wanita","dompet lucu"] },
  { c:"Tas Wanita", s:"Clutch & Tas Pesta", adm:9.0, mall:10.2, ox:"G",
    k:["clutch","tas pesta","evening bag","tas kondangan","minaudiere","tas pernikahan"] },
  { c:"Tas Wanita", s:"Aksesoris Tas", adm:9.0, mall:10.2, ox:"G",
    k:["tali tas","gantungan tas","organizer tas","tas dalam tas","bag organizer",
       "liner tas","strap tas","bag charm","bag hook"] },

  /* ===================== FMCG ===================== */
  // Ibu & Bayi
  { c:"Ibu & Bayi", s:"Susu Formula & Makanan Bayi", adm:6.75, mall:7.2, ox:"D",
    k:["susu formula","sufor","bubur bayi","sereal bayi","camilan bayi","makanan bayi",
       "mpasi","puree bayi","biscuit bayi","finger food bayi","snack bayi","susu bayi",
       "formula milk","susu lactogen","susu bebelac","susu enfamil","susu frisian flag"] },
  { c:"Ibu & Bayi", s:"Popok & Pispot", adm:9.0, mall:9.95, ox:"D",
    k:["popok","diapers","pampers","popok kain","pispot","perlak","popok celana","diaper pants",
       "popok newborn","popok bayi","nappy","diaper bag","training pants","potty"] },
  { c:"Ibu & Bayi", s:"Perlengkapan Makan Bayi", adm:8.25, mall:7.7, ox:"D",
    k:["botol susu","dot bayi","pompa asi","sterilizer","kursi makan bayi","peralatan makan bayi",
       "sendok bayi","mangkuk bayi","piring bayi","gelas bayi","breast pump","nursing pad",
       "kantong asi","cooler bag asi","botol kaca bayi","straw cup bayi","sippy cup"] },
  { c:"Ibu & Bayi", s:"Perlengkapan Mandi Bayi", adm:8.25, mall:7.7, ox:"D",
    k:["sabun bayi","shampo bayi","bak mandi bayi","handuk bayi","parfum bayi","tisu basah bayi",
       "cotton bud bayi","kapas bayi","baby wash","baby shampoo","baby oil bayi","bath support"] },
  { c:"Ibu & Bayi", s:"Kesehatan & Perawatan Bayi", adm:8.25, mall:7.2, ox:"D",
    k:["minyak telon","bedak bayi","baby lotion","vitamin bayi","perawatan bayi","termometer bayi",
       "aspirator hidung","nail clipper bayi","teether","gigitan bayi","obat batuk bayi",
       "obat demam bayi","baby cream","salep bayi","minyak kayu putih"] },
  { c:"Ibu & Bayi", s:"Kamar Bayi", adm:8.25, mall:10.2, ox:"D",
    k:["box bayi","ayunan bayi","baby walker","bedong","selimut bayi","kasur bayi","bantal bayi",
       "sprei bayi","kelambu bayi","baby bouncer","baby swing","tempat tidur bayi","ranjang bayi"] },
  { c:"Ibu & Bayi", s:"Perlengkapan Travelling Bayi", adm:9.0, mall:10.2, ox:"D",
    k:["stroller","gendongan bayi","car seat","kereta bayi","tas bayi","carrier bayi",
       "ergo baby","babyzen","stroller lipat","infant seat","baby carrier","sling","wrap"] },
  { c:"Ibu & Bayi", s:"Kehamilan & Ibu Hamil", adm:9.0, mall:10.2, ox:"D",
    k:["susu ibu hamil","vitamin ibu hamil","bantal hamil","penyangga perut","test pack",
       "pregnancy test","vitamin folat","asam folat","prenatal vitamin","nursing pillow"] },
  { c:"Ibu & Bayi", s:"Mainan Bayi & Anak", adm:9.0, mall:7.7, ox:"H",
    k:["mainan","mainan bayi","mainan edukasi","boneka","puzzle","mainan anak","lego","slime",
       "playdoh","clay","mainan masak-masakan","mainan pasir","action figure anak",
       "remote control car","drone mainan","robot mainan","sepeda anak","skuter anak"] },

  // Kesehatan
  { c:"Kesehatan", s:"Hand Sanitizer", adm:10.0, mall:10.2, ox:"E",
    k:["hand sanitizer","sanitizer","gel cuci tangan","antiseptik tangan","hand rub",
       "disinfektan tangan","sabun antiseptik"] },
  { c:"Kesehatan", s:"Obat-obatan & Alat Kesehatan", adm:9.5, mall:7.2, ox:"E",
    k:["obat","obat warung","p3k","plester","perban","termometer","tensimeter","alat tes gula darah",
       "kursi roda","masker medis","sarung tangan medis","nebulizer","oksimeter","oximeter",
       "pulse oximeter","glucometer","blood pressure monitor","obat herbal","jamu","obat tradisional",
       "betadine","rivanol","alkohol","kassa steril","suhu badan","tetes mata"] },
  { c:"Kesehatan", s:"Suplemen Makanan", adm:9.0, mall:7.2, ox:"E",
    k:["vitamin","suplemen","multivitamin","kolagen","suplemen diet","omega 3","fish oil",
       "zinc","vitamin c","vitamin d","vitamin e","vitamin b complex","magnesium","kalsium",
       "probiotik","protein powder","whey protein","propolis","bee pollen","royal jelly",
       "madu herbal","suplemen imun","collagen drink","spirulina","chlorella","madu manuka"] },
  { c:"Kesehatan", s:"Perawatan Diri (Kesehatan)", adm:9.0, mall:7.2, ox:"E",
    k:["sikat gigi","pasta gigi","obat kumur","pembalut","anti nyamuk","perawatan gigi",
       "benang gigi","dental floss","water flosser","pemutih gigi","whitening strip",
       "karang gigi","tisu basah","kapas","cotton bud","pembersih kewanitaan",
       "pembalut wanita","pantyliner","tampon","menstrual cup","alat cukur elektrik"] },
  { c:"Kesehatan", s:"Kesehatan Seksual", adm:9.0, mall:7.7, ox:"D",
    k:["kondom","pelumas","alat bantu","kontrasepsi","family planning"] },
  { c:"Kesehatan", s:"Lensa Kontak", adm:9.0, mall:8.0, ox:"H",
    k:["softlens","lensa kontak","contact lens","cairan softlens","daily contact","monthly lens",
       "colored contact","lens plus","softlens bening","softlens warna","eye drop"] },
  { c:"Kesehatan", s:"Popok Dewasa", adm:9.0, mall:7.2, ox:"D",
    k:["popok dewasa","adult diapers","popok lansia","underpads","pengalas tempat tidur",
       "incontinence pad"] },

  // Makanan & Minuman
  { c:"Makanan & Minuman", s:"Makanan Ringan", adm:10.0, mall:10.2, ox:"E",
    k:["snack","makanan ringan","keripik","biskuit","wafer","kerupuk","permen","cokelat",
       "kacang","cemilan","dendeng","abon","rumput laut","popcorn","nachos","pretzel",
       "agar-agar","jelly","puding","marshmallow","gummy","candy","chips","crackers",
       "kacang mete","kacang almond","kacang goreng","pilus","chitato","lays","taro",
       "oreo","ritz","good time","choki choki","yupi","beng-beng","silverqueen"] },
  { c:"Makanan & Minuman", s:"Minuman", adm:9.0, mall:10.2, ox:"E",
    k:["kopi","teh","minuman","sirup","jus","susu non dairy","minuman serbuk","minuman energi",
       "thai tea","matcha","boba","cold brew","susu almond","oat milk","susu kedelai",
       "sari buah","minuman isotonik","air mineral","vitamin c drink","teh hijau","green tea",
       "herbal tea","chamomile","jahe","wedang","lemon tea","es teh","minuman herbal",
       "soda","minuman berkarbonasi","sparkling water","tonic water","minuman kemasan"] },
  { c:"Makanan & Minuman", s:"Minuman Alkohol", adm:9.0, mall:10.2, ox:"E",
    k:["bir","wine","champagne","whiskey","vodka","sake","soju","rum","gin","tequila",
       "minuman beralkohol","cider","mead","liqueur"] },
  { c:"Makanan & Minuman", s:"Bahan Pokok / Sembako", adm:6.75, mall:6.2, ox:"E",
    k:["beras","mie","pasta","makanan kaleng","bahan pokok","sembako","seafood kering",
       "biji-bijian","gaplek","jagung","kedelai","kacang hijau","kacang merah","lentil",
       "quinoa","oatmeal","sagu","singkong kering","kentang kering","beras merah","beras organik",
       "beras basmati","beras jasmine","beras pulen","beras premium","beras analog"] },
  { c:"Makanan & Minuman", s:"Kebutuhan Memasak / Bumbu", adm:6.75, mall:7.2, ox:"E",
    k:["minyak goreng","garam","gula","kecap","saus","sambal","bumbu masak","tepung bumbu",
       "lada","rempah","kecap manis","saus tiram","terasi","kaldu bubuk","msg","micin",
       "santan","saus sambal","saus tomat","mayonaise","vinegar","cuka","oregano",
       "kayu manis","cengkeh","kapulaga","kemiri","kunyit","jahe","lengkuas","sereh",
       "penyedap rasa","royco","masako","saori","abc kecap","bango"] },
  { c:"Makanan & Minuman", s:"Bahan Baking", adm:6.75, mall:6.2, ox:"E",
    k:["tepung","tepung terigu","baking powder","pewarna makanan","bahan kue","penyedap kue",
       "soda kue","tepung premix","yeast","ragi","vanili","coklat bubuk","cacao","cocoa",
       "gula halus","gula pasir","mentega putih","shortening","susu bubuk baking",
       "dark chocolate","white chocolate","baking soda","cream of tartar","almond flour",
       "tepung gandum","tepung beras","tapioka","maizena"] },
  { c:"Makanan & Minuman", s:"Makanan Instan", adm:9.0, mall:7.2, ox:"E",
    k:["mie instan","makanan instan","makanan siap saji","bubur instan","hotpot instan",
       "indomie","mie goreng","mie kuah","bihun","soun","kwetiau instan","nasi instan",
       "nasi goreng instan","pasta instan","mac and cheese","sup instan","kaldu instan",
       "oatmeal instan","sereal instan"] },
  { c:"Makanan & Minuman", s:"Susu & Olahan", adm:8.25, mall:9.95, ox:"E",
    k:["susu","susu uht","susu bubuk","keju","yogurt","mentega","margarin","krimer","es krim",
       "susu segar","yoghurt","cream cheese","cottage cheese","mozzarella","tahu susu",
       "susu full cream","susu skim","susu evaporasi","susu kental manis","susu fermentasi",
       "kefir","butter","whipped cream"] },
  { c:"Makanan & Minuman", s:"Telur", adm:6.5, mall:7.2, ox:"E",
    k:["telur","telur ayam","telur bebek","telur puyuh","telur asin","telur omega",
       "telur kampung","telur organik","telur rebus"] },
  { c:"Makanan & Minuman", s:"Roti & Kue", adm:9.0, mall:10.2, ox:"E",
    k:["roti","kue","pastry","pie","bakery","brownies","cookies","kukis","cake","donat",
       "croissant","baguette","sourdough","roti gandum","roti tawar","roti manis",
       "muffin","cupcake","tart","cheesecake","bolu","lapis legit","nastar","kastengel",
       "kue kering","kukis lebaran","hampers kue"] },
  { c:"Makanan & Minuman", s:"Menu Sarapan", adm:6.75, mall:10.2, ox:"E",
    k:["madu","selai","sereal","granola","oat","madu akasia","madu randu","madu multiflora",
       "madu hutan","madu murni","madu asli","madu lebah","madu trigona","sirup maple",
       "selai kacang","peanut butter","selai cokelat","nutella","hazelnut spread",
       "granola bar","oatmeal","rolled oat","instant oat","overnight oat","cereal bar",
       "muesli","cornflakes","rice krispies","susu sereal","madu pahit","madu manis"] },
  { c:"Makanan & Minuman", s:"Makanan Segar & Beku", adm:6.75, mall:9.95, ox:"E",
    k:["daging","ayam","ikan","udang","sayur","buah","frozen food","makanan beku","seafood",
       "nugget","sosis","bakso","dimsum","gyoza","siomay","batagor","tempura","spring roll",
       "tempe","tahu","jamur","jamur tiram","jamur shiitake","tahu bulat","sayuran segar",
       "buah segar","buah impor","alpukat","mangga","kurma","buah kering","frozen beef",
       "frozen salmon","fillet ikan","udang kupas","cumi","kerang","daging sapi","daging kambing"] },
  { c:"Makanan & Minuman", s:"Set Hadiah & Hampers", adm:9.0, mall:10.2, ox:"E",
    k:["hampers","parcel","paket hadiah","gift set makanan","kado lebaran","kado natal",
       "hampers lebaran","hampers natal","hampers birthday","snack box","premium hampers"] },

  // Perawatan & Kecantikan
  { c:"Perawatan & Kecantikan", s:"Perawatan Wajah / Skincare", adm:8.25, mall:9.95, ox:"D",
    k:["skincare","perawatan wajah","serum","toner","pelembab","sunscreen","masker wajah",
       "facial wash","moisturizer","cleanser","micellar water","essence","emulsion",
       "retinol","vitamin c serum","niacinamide","hyaluronic acid","spf","uv protection",
       "eye cream","face oil","face mist","sheet mask","clay mask","peel off mask",
       "acne treatment","jerawat","pembersih pori","exfoliant","aha bha","peeling",
       "cetaphil","wardah","skintific","somethinc","the ordinary","emina","avoskin"] },
  { c:"Perawatan & Kecantikan", s:"Kosmetik / Make Up", adm:8.25, mall:9.95, ox:"D",
    k:["kosmetik","make up","lipstik","bedak","foundation","maskara","eyeliner","blush on",
       "concealer","eyeshadow","bronzer","highlighter","setting spray","primer",
       "lip tint","lip gloss","lip balm","bb cream","cc cream","cushion","contouring",
       "eyebrow pencil","mascara","false lashes","bulu mata palsu","lip liner",
       "makeup remover","micellar makeup remover","wardah kosmetik","maybelline","nyx"] },
  { c:"Perawatan & Kecantikan", s:"Perawatan Tubuh", adm:8.25, mall:9.95, ox:"D",
    k:["sabun mandi","body lotion","deodoran","body scrub","lulur","handbody","sunscreen tubuh",
       "shower gel","body wash","sabun cair","bath bomb","body butter","body oil","milk bath",
       "scrub gula","coffee scrub","whitening body","body serum","anti aging tubuh",
       "roll on","deo stick","antiperspiran","sabun kojic","sabun glutathione"] },
  { c:"Perawatan & Kecantikan", s:"Perawatan Rambut", adm:8.25, mall:9.95, ox:"D",
    k:["shampo","conditioner","vitamin rambut","cat rambut","hair tonic","masker rambut",
       "hair mask","hair serum","hair oil","minyak rambut","hair spray","dry shampoo",
       "leave in conditioner","hair treatment","protein hair","keratin","rebonding cream",
       "hair color","bleaching rambut","tonic rambut rontok","shampoo anti ketombe"] },
  { c:"Perawatan & Kecantikan", s:"Parfum & Wewangian", adm:8.25, mall:9.95, ox:"D",
    k:["parfum","minyak wangi","body mist","cologne","eau de toilette","eau de parfum",
       "parfum pria","parfum wanita","roll on parfum","parfum sholat","minyak oud",
       "reed diffuser","spray parfum","parfum mobil","aromaterapi","wewangian"] },
  { c:"Perawatan & Kecantikan", s:"Alat Kecantikan", adm:8.25, mall:9.95, ox:"D",
    k:["alat make up","kuas make up","beauty blender","hair dryer","catokan","alat kecantikan",
       "cermin","sisir","hair straightener","curling iron","curling wand","hot comb",
       "hair curler","facial steamer","alat pembersih wajah","face roller","gua sha",
       "LED mask","microneedle","epilator","alat penghilang bulu","IPL","razor elektrik",
       "pinset","gunting rambut","clipper rambut","kuas foundation"] },
  { c:"Perawatan & Kecantikan", s:"Perawatan Tangan, Kaki & Kuku", adm:8.25, mall:9.95, ox:"D",
    k:["kutek","cat kuku","kuku palsu","nail art","perawatan kuku","hand cream",
       "nail extension","acrylic nail","gel nail","nail gel","nail lamp","nail drill",
       "cuticle oil","nail remover","aceton","stiker kuku","nail foil","base coat","top coat",
       "foot mask","foot cream","foot scrub","crack heel","tumit retak"] },
  { c:"Perawatan & Kecantikan", s:"Perawatan Pria (Grooming)", adm:8.25, mall:9.95, ox:"D",
    k:["alat cukur","pisau cukur","pomade","grooming pria","perawatan pria","shaving cream",
       "after shave","beard oil","beard balm","kumis","jenggot","trimmer","pencukur kumis",
       "hair wax","hair clay","gel rambut","minyak rambut pria","wax pomade"] },

  /* ===================== LIFESTYLE ===================== */
  // Buku & Alat Tulis
  { c:"Buku & Alat Tulis", s:"Alat Tulis", adm:9.0, mall:7.2, ox:"D",
    k:["pulpen","pensil","spidol","penghapus","tipe x","highlighter","alat tulis","atk",
       "pulpen tinta","ballpoint","gel pen","fountain pen","marker","stabilo","correction pen",
       "mechanical pencil","art pen","liner","fineliner"] },
  { c:"Buku & Alat Tulis", s:"Perlengkapan Sekolah & Kantor", adm:9.0, mall:7.2, ox:"D",
    k:["kalkulator","gunting","lem","stapler","selotip","penggaris","tempat pensil","papan tulis",
       "whiteboard","cutter","pisau cutter","paper clip","binder clip","push pin","paku payung",
       "pembolong kertas","stempel","tinta stempel","laminator","binding","printer label",
       "name tag","lanyard","filing","map","ordner","stopmap"] },
  { c:"Buku & Alat Tulis", s:"Perlengkapan Menggambar", adm:10.0, mall:11.7, ox:"D",
    k:["pensil warna","crayon","cat air","cat akrilik","kuas lukis","kanvas","buku gambar",
       "watercolor","oil paint","acrylic paint","gouache","pastel","charcoal","sketsa",
       "art journal","sketchbook","drawing pad","manga pen","comic pen"] },
  { c:"Buku & Alat Tulis", s:"Buku Tulis & Kertas", adm:9.0, mall:9.95, ox:"E",
    k:["buku tulis","kertas","kertas hvs","notebook","sticky notes","label","stiker",
       "buku agenda","diary","planner","post it","memo","kertas origami","art paper",
       "kraft paper","kertas karton","buku sketsa","loose leaf","ring binder"] },
  { c:"Buku & Alat Tulis", s:"Pembungkus Kado & Kemasan", adm:9.5, mall:7.7, ox:"G",
    k:["kertas kado","kardus","bubble wrap","kotak kado","pita kado","tas kado","packaging",
       "bungkus kado","wrapping paper","gift bag","gift box","ampelas bubble","packing tape",
       "ziplock","plastik klip","kantong plastik","food grade packaging"] },

  // Buku & Majalah
  { c:"Buku & Majalah", s:"Buku Bacaan", adm:9.0, mall:7.2, ox:"E",
    k:["buku","novel","buku pelajaran","buku anak","buku resep","komik","buku agama",
       "buku self help","buku bisnis","buku investasi","buku motivasi","manga","manhwa",
       "light novel","buku memasak","buku fiksi","thriller","romance novel","buku nonfiksi"] },
  { c:"Buku & Majalah", s:"Majalah & Koran", adm:10.0, mall:11.7, ox:"D",
    k:["majalah","koran","tabloid","majalah wanita","majalah otomotif","majalah bisnis"] },
  { c:"Buku & Majalah", s:"E-Book", adm:9.0, mall:7.7, ox:"D",
    k:["ebook","e-book","buku digital","pdf buku","buku elektronik"] },

  // Hewan Peliharaan
  { c:"Hewan Peliharaan", s:"Makanan Hewan", adm:9.5, mall:7.7, ox:"H",
    k:["makanan kucing","makanan anjing","pakan hewan","snack kucing","cat food","dog food",
       "pakan burung","makanan ikan hias","pakan hamster","makanan kelinci","makanan reptil",
       "royal canin","whiskas","friskies","pro plan","hills","acana","orijen","wet food kucing",
       "dry food anjing","frozen food ikan","cacing","jangkrik"] },
  { c:"Hewan Peliharaan", s:"Aksesoris Hewan Peliharaan", adm:9.5, mall:7.7, ox:"H",
    k:["kandang","mainan kucing","tempat makan hewan","kalung hewan","aquarium","tempat tidur hewan",
       "scratching post","cat tree","litter box","aquarium fish tank","kandang burung",
       "kandang hamster","carrier hewan","pet carrier","tempat minum hewan","sangkar"] },
  { c:"Hewan Peliharaan", s:"Litter & Toilet Hewan", adm:9.5, mall:7.7, ox:"H",
    k:["pasir kucing","litter box","popok hewan","training pad","cat litter","bentonite litter",
       "tofu litter","crystal litter","puppy pad","pispot kucing"] },
  { c:"Hewan Peliharaan", s:"Grooming Hewan", adm:9.5, mall:7.7, ox:"G",
    k:["shampo hewan","grooming","perawatan hewan","sisir hewan","shampo kucing","shampo anjing",
       "sisir bulu","nail clipper hewan","gunting bulu","dryer hewan"] },
  { c:"Hewan Peliharaan", s:"Perawatan Kesehatan Hewan", adm:9.5, mall:7.7, ox:"G",
    k:["vitamin hewan","obat kutu","obat hewan","suplemen hewan","obat cacing hewan",
       "flea collar","tick collar","frontline","advocate","spot on kutu"] },
  { c:"Hewan Peliharaan", s:"Pakaian & Aksesoris Hewan", adm:9.5, mall:7.7, ox:"G",
    k:["baju hewan","baju kucing","baju anjing","aksesoris hewan","harness","tali anjing",
       "leash","collar anjing","tag nama hewan","kostum hewan","topi hewan"] },

  // Hobi & Koleksi
  { c:"Hobi & Koleksi", s:"Alat & Aksesoris Musik", adm:9.5, mall:7.7, ox:"E",
    k:["gitar","keyboard musik","piano","ukulele","alat musik","drum","biola","gitar akustik",
       "gitar elektrik","bass guitar","gitar klasik","cajon","kulintang","angklung","seruling",
       "harmonika","picking gitar","string gitar","senar gitar","capo","gig bag gitar",
       "tuner","metronome","gitar mini","keytar"] },
  { c:"Hobi & Koleksi", s:"Koleksi (Action Figure, dll)", adm:9.5, mall:7.7, ox:"H",
    k:["action figure","koleksi","diecast","figure","patung","koin","koleksi anime",
       "gundam","model kit","nendoroid","figma","pop figure","hot wheels","tomica",
       "vintage","vinyl figure","blind box","pop mart","molly","labubu"] },
  { c:"Hobi & Koleksi", s:"Mainan & Games (Hobi)", adm:9.5, mall:7.7, ox:"H",
    k:["board game","kartu","rubik","yoyo","kartu remi","mainan dewasa","uno",
       "jenga","monopoly","card game","tabletop game","catur","dart","kendama",
       "speed cube","magnetic cube","magic trick"] },
  { c:"Hobi & Koleksi", s:"Souvenir & Hadiah", adm:9.0, mall:10.45, ox:"G",
    k:["souvenir","gantungan kunci","celengan","magnet kulkas","kipas tangan","hampers",
       "gift set","paket hadiah","bingkisan","souvenir pernikahan","souvenir ulang tahun",
       "souvenir wisuda","merchandise","custom souvenir","pin","badge","sticker"] },
  { c:"Hobi & Koleksi", s:"Perlengkapan Menjahit & Kerajinan", adm:9.5, mall:7.7, ox:"F",
    k:["benang","jarum jahit","perlengkapan menjahit","kain flanel","resleting","kancing",
       "pita","renda","elastis","dacron","kapas isian","kain","bahan kain","craft kit",
       "resin kit","macrame","cross stitch","embroidery","sulam"] },

  // Mobil
  { c:"Mobil", s:"Aksesoris Eksterior Mobil", adm:8.25, mall:10.45, ox:"G",
    k:["sarung mobil","cover mobil","spion mobil","talang air","stiker mobil","emblem mobil",
       "klakson","antena mobil","karpet lumpur","plat nomor","chrome trim","door visor",
       "side mirror cover","body kit","roof rack","bike rack"] },
  { c:"Mobil", s:"Aksesoris Interior Mobil", adm:8.25, mall:10.45, ox:"G",
    k:["jok mobil","sarung jok","karpet mobil","parfum mobil","setir mobil","holder hp mobil",
       "kamera parkir","head unit","dashcam","kamera belakang mobil","sun shading","kaca film",
       "floor mat","organizer mobil","bantal mobil","aroma mobil","usb charger mobil",
       "bluetooth transmitter","hud display","speedometer digital"] },
  { c:"Mobil", s:"Suku Cadang Mobil", adm:9.5, mall:10.45, ox:"G",
    k:["sparepart mobil","ban mobil","velg mobil","aki mobil","busi","lampu mobil","filter oli",
       "kampas rem","shockbreaker","timing belt","alternator","radiator","water pump",
       "kopling","catalytic converter","sensor mobil","wiper","wiper blade","filter udara"] },
  { c:"Mobil", s:"Oli & Pelumas Kendaraan", adm:9.0, mall:10.45, ox:"G",
    k:["oli mobil","oli mesin","pelumas","coolant","minyak rem","oli transmisi","grease",
       "cairan power steering","radiator coolant","oli gardan","castrol","shell","pertamina fastron",
       "mobil 1","total quartz","motul"] },
  { c:"Mobil", s:"Perawatan Kendaraan", adm:8.25, mall:10.45, ox:"G",
    k:["sabun mobil","wax mobil","poles mobil","pembersih kaca mobil","perawatan mobil",
       "car shampoo","car wax","polish","ceramic coating","nano coating","rim cleaner",
       "engine cleaner","interior cleaner","kain mikrofiber","foam gun","snow foam"] },

  // Sepeda Motor
  { c:"Sepeda Motor", s:"Suku Cadang Motor", adm:8.25, mall:10.45, ox:"G",
    k:["sparepart motor","ban motor","velg motor","aki motor","busi motor","kampas rem motor",
       "rantai motor","gir","cdi","knalpot motor","lampu motor","busi iridium","busi ngk",
       "filter udara motor","karburator","injektor","stang motor","bearing motor","as motor"] },
  { c:"Sepeda Motor", s:"Aksesoris Sepeda Motor", adm:8.25, mall:10.45, ox:"G",
    k:["aksesoris motor","spion motor","jok motor","box motor","sarung motor","karpet motor",
       "stiker motor","cover motor","gps motor","holder hp motor","tas motor","windshield",
       "footpeg","hand grip","throttle grip","bar end","knalpot racing"] },
  { c:"Sepeda Motor", s:"Helm & Aksesoris Pengendara", adm:8.25, mall:10.45, ox:"G",
    k:["helm","helm motor","helm full face","kaca helm","sarung tangan motor","jaket motor",
       "celana motor","sepatu motor","helm half face","helm open face","helm sni",
       "rain coat motor","jas hujan motor","helm anak","masker motor","balaclava"] },

  // Olahraga & Outdoor
  { c:"Olahraga & Outdoor", s:"Alat Rekreasi Olahraga & Outdoor", adm:10.0, mall:11.7, ox:"H",
    k:["sepeda","tenda","alat fitness","raket","bola","matras yoga","dumbbell","alat pancing",
       "helm sepeda","skateboard","camping","barbel","kettlebell","resistance band",
       "pull up bar","push up stand","ab wheel","treadmill","sepeda statis","elliptical",
       "raket badminton","shuttlecock","raket tenis","bola basket","bola sepak","bola voli",
       "joran pancing","reel pancing","umpan pancing","tali skipping","jump rope","boxing",
       "sarung tinju","sleeping bag","flysheet","matras camping","kompor camping","carrier"] },
  { c:"Olahraga & Outdoor", s:"Pakaian Olahraga", adm:10.0, mall:11.7, ox:"H",
    k:["baju olahraga","jersey","baju renang","legging olahraga","sports bra","celana olahraga",
       "baju gym","tank top olahraga","rashguard","wetsuit","baju badminton","baju futsal",
       "jersey bola","celana pendek olahraga","training suit","tracsuit","pakaian lari",
       "compression pants","cycling jersey","baju yoga"] },
  { c:"Olahraga & Outdoor", s:"Sepatu Olahraga", adm:10.0, mall:11.7, ox:"H",
    k:["sepatu olahraga","sepatu lari","sepatu futsal","sepatu basket","sepatu hiking",
       "sepatu badminton","sepatu tenis","sepatu voli","sepatu sepak bola","trail shoes",
       "running shoes","sepatu gym","sepatu bola indoor","futsal shoes"] },
  { c:"Olahraga & Outdoor", s:"Aksesoris Olahraga & Outdoor", adm:10.0, mall:11.7, ox:"H",
    k:["payung","tas olahraga","alat training","pelindung gym","stopwatch","topi olahraga",
       "gym bag","sport bag","gloves gym","wrist wrap","knee support","ankle support",
       "body protector","shin guard","pelindung siku","kacamata renang","topi renang",
       "speedometer sepeda","cycling gloves","bottle sport","water bottle gym"] },

  // Perlengkapan Rumah
  { c:"Perlengkapan Rumah", s:"Perlengkapan Dapur", adm:10.0, mall:11.7, ox:"D",
    k:["panci","wajan","penggorengan","pisau dapur","talenan","spatula","rak dapur","wadah makanan",
       "tupperware","saringan","cetakan kue","loyang","timbangan dapur","steamer",
       "panci teflon","teflon anti lengket","wajan besi","cobek","ulekan","blender manual",
       "food container","toples","mangkok stainless","sendok masak","sutil","serok",
       "pengocok telur","teko","gelas takar","cangkir kopi","moka pot manual","french press",
       "food sealer","manual slicer","mandoline","peeler sayur","parutan","colander"] },
  { c:"Perlengkapan Rumah", s:"Peralatan Makan", adm:10.0, mall:11.7, ox:"D",
    k:["piring","gelas","mangkuk","sendok","garpu","botol minum","tumbler","cangkir","mug",
       "termos","lunchbox","kotak bekal","bento box","straw","sedotan","piring melamin",
       "piring keramik","set makan","cutlery","chopstick","sumpit","pisau makan","teko susu",
       "water pitcher","vacuum flask","insulated bottle","travel mug"] },
  { c:"Perlengkapan Rumah", s:"Pengharum Ruangan & Aromaterapi", adm:10.0, mall:11.7, ox:"D",
    k:["pengharum ruangan","diffuser","aromaterapi","minyak esensial","lilin aroma",
       "reed diffuser","electric diffuser","humidifier aromaterapi","wewangian ruangan",
       "car freshener","glade","wipol","baygon","obat nyamuk","electric mosquito"] },
  { c:"Perlengkapan Rumah", s:"Furniture", adm:10.0, mall:11.7, ox:"F",
    k:["kursi","meja","lemari","sofa","rak","meja tulis","bangku","lemari pakaian","kabinet",
       "rak buku","meja makan","kursi makan","kursi gaming","gaming chair","sofa bed",
       "meja kerja","study desk","standing desk","rak dinding","floating shelf","shoe rack",
       "lemari sepatu","nakas","meja kopi","coffee table","tv stand","buffet"] },
  { c:"Perlengkapan Rumah", s:"Kamar Tidur (Kasur, Sprei)", adm:10.0, mall:11.7, ox:"F",
    k:["kasur","matras","sprei","bantal","guling","selimut","sarung bantal","bed cover",
       "bedsheet","bed runner","duvet","comforter","kasur lipat","kasur angin","kasur busa",
       "spring bed","memory foam","sarung guling","pelindung matras","bed protector",
       "sleeping bag","bantal latex","bantal dakron","bantal memory foam"] },
  { c:"Perlengkapan Rumah", s:"Lampu", adm:9.5, mall:7.7, ox:"F",
    k:["lampu","lampu led","bohlam","lampu hias","lampu tidur","downlight","lampu sorot",
       "lampu meja","floor lamp","lampu dinding","fairy lights","string light","neon flex",
       "led strip","philips led","osram","lampu emergency","emergency light","lampu taman"] },
  { c:"Perlengkapan Rumah", s:"Dekorasi Rumah", adm:10.0, mall:10.45, ox:"H",
    k:["dekorasi","bingkai foto","jam dinding","cermin","wallpaper","stiker dinding","vas","karpet",
       "tirai","gorden","keset","tanaman artifisial","pigura","lukisan","poster","photo frame",
       "bohemian decor","macrame","dream catcher","aksesoris rumah","hiasan dinding",
       "dekorasi kamar","tapestry","wall art"] },
  { c:"Perlengkapan Rumah", s:"Organizer Rumah", adm:10.0, mall:11.7, ox:"H",
    k:["organizer","box penyimpanan","keranjang","gantungan","rak sepatu","tempat tisu",
       "laundry bag","storage box","ziplock","plastik klip","vacuum bag","hanging organizer",
       "drawer organizer","desk organizer","cable organizer","charging station","cable management",
       "tempat remote","tempat kunci","wall organizer","wardrobe organizer"] },
  { c:"Perlengkapan Rumah", s:"Perawatan Rumah (Pembersih)", adm:10.0, mall:11.7, ox:"H",
    k:["sapu","pel","detergen","pembersih","tisu","tisu toilet","kemoceng","tempat sampah",
       "pewangi pakaian","pelembut","sabun cuci","bayclin","vixal","wipol","karbol","kain lap",
       "microfiber","spons cuci","scouring pad","sikat","sikat botol","toilet brush",
       "pembersih kerak","pembersih kapur","mop","mop bucket","sweeper","window cleaner"] },
  { c:"Perlengkapan Rumah", s:"Alat Pertukangan & Renovasi", adm:10.0, mall:11.7, ox:"G",
    k:["bor","obeng","palu","tang","kunci pas","cat tembok","gergaji","gerinda","tool box",
       "paku","amplas","tangga","meteran","waterpass","cutter besar","plamir","kuas cat",
       "roller cat","thinner","mur baut","electric drill","impact driver","angle grinder",
       "palu besi","kunci inggris","kikir","heat gun","solder"] },
  { c:"Perlengkapan Rumah", s:"Kamar Mandi", adm:10.0, mall:11.7, ox:"G",
    k:["kloset","shower","handuk","gayung","ember","tirai kamar mandi","rak kamar mandi",
       "wastafel","cermin kamar mandi","dispenser sabun","sabun cair","shower head",
       "bathroom set","tempat sikat gigi","sikat toilet","wc duduk","shower filter",
       "bath mat","non slip mat","bathroom organizer","rak sudut kamar mandi"] },
  { c:"Perlengkapan Rumah", s:"Taman & Berkebun", adm:10.0, mall:11.7, ox:"G",
    k:["tanaman","pot","pupuk","bibit","media tanam","alat berkebun","selang air","mesin potong rumput",
       "tanaman hias","kaktus","sukulen","monstera","pothos","aglonema","bibit sayuran",
       "sekop","cangkul","cetok","penyiram tanaman","sprayer","pupuk organik","tanah pot",
       "cocopeat","perlite","hidroponik","aquaponik","vertikal garden","polybag","greenhouse"] },
  { c:"Perlengkapan Rumah", s:"Alat Pengaman", adm:10.0, mall:11.7, ox:"G",
    k:["brankas","gembok","cctv rumah","pemadam api","kunci pintu","alat pengaman",
       "smart lock","fingerprint door lock","padlock","kunci kombinasi","alarm rumah",
       "smoke detector","carbon monoxide detector","fire extinguisher","pemadam kebakaran"] },
  { c:"Perlengkapan Rumah", s:"Perlengkapan Pesta", adm:10.0, mall:11.7, ox:"G",
    k:["balon","dekorasi pesta","backdrop","kartu ucapan","topi pesta","perlengkapan ulang tahun",
       "party decoration","banner ulang tahun","confetti","party popper","dekorasi wedding",
       "perlengkapan nikahan","photo booth props","table runner","lilin ulang tahun"] },
  { c:"Perlengkapan Rumah", s:"Perlengkapan Keagamaan", adm:10.0, mall:11.7, ox:"D",
    k:["perlengkapan keagamaan","tasbih","alkitab","dupa","peralatan ibadah","al quran",
       "rohani","tempat lilin gereja","salib","patung","menorah","siddur","komuni"] },
  { c:"Perlengkapan Rumah", s:"Perlengkapan Dapur (Sealer)", adm:6.5, mall:7.2, ox:"D",
    k:["sealer","vacuum sealer","impulse sealer","bag sealer","food saver","penyegel kantong"] },

  /* ===================== TIKET, VOUCHER & LAYANAN ===================== */
  { c:"Tiket, Voucher & Layanan", s:"Pulsa & Data", adm:9.5, mall:7.7, ox:"D",
    k:["pulsa","paket data","kuota","token listrik","telco","internet","wifi voucher",
       "telkomsel","xl","indosat","tri","smartfren","by.u","paket nelpon"] },
  { c:"Tiket, Voucher & Layanan", s:"Voucher Gaming", adm:9.0, mall:7.7, ox:"D",
    k:["voucher game","top up game","diamond","gaming voucher","mobile legends","free fire",
       "pubg","cod mobile","genshin impact","valorant","steam wallet","google play",
       "app store","roblox robux","minecraft","top up ff","top up ml"] },
  { c:"Tiket, Voucher & Layanan", s:"E-Money", adm:8.25, mall:7.2, ox:"G",
    k:["e-money","saldo","top up e-wallet","gopay","ovo","dana","shopeepay","linkaja",
       "emoney","kartu e-money","mandiri e-money","brizzi","flazz","tap cash"] },
  { c:"Tiket, Voucher & Layanan", s:"Tiket Event & Travel", adm:9.5, mall:7.7, ox:"D",
    k:["tiket event","tiket konser","voucher hotel","tiket pesawat","paket tour","streaming",
       "tiket bioskop","netflix","spotify","disney plus","youtube premium","tiket wisata",
       "voucher spa","voucher restoran","tiket theme park","tiket kereta"] }
];
